/**
 * LowKeySigns - Civic Counter Context Definition
 * Challenge: HTH-CV-09 (Accessibility-First Sign Language Communication Bridge)
 * 
 * Maps each of the 20 locked vocabulary words to comprehensive public-service
 * counter operational protocols across Hospitals, Government Desks, and Banks.
 */

export interface CivicActionProtocol {
  word: string;
  category: 'Medical & Triage' | 'Civic Administration' | 'Financial & Payment' | 'Queue & Navigation' | 'Dialogue & Civility';
  urgency: 'critical' | 'high' | 'standard' | 'courtesy';
  icon: string;
  civicDomain: string;
  intentSummary: string;
  clerkAction: string;
  visitorAssurance: string;
  recommendedNextSign: string;
  quickStaffReplies: string[];
}

export const CIVIC_CONTEXT_MAP: Record<string, CivicActionProtocol> = {
  help: {
    word: 'help',
    category: 'Medical & Triage',
    urgency: 'critical',
    icon: 'AlertTriangle',
    civicDomain: 'Priority Counter Assistance',
    intentSummary: 'Visitor requires urgent guidance or personal assistance at this counter.',
    clerkAction: 'Acknowledge immediately. Stand or lean forward, make eye contact, and offer one-on-one guided service.',
    visitorAssurance: 'We are here to help you. A dedicated counter officer is assisting you now.',
    recommendedNextSign: 'please',
    quickStaffReplies: ['I am here to assist you.', 'Please take a seat right here.', 'How can I assist today?'],
  },
  emergency: {
    word: 'emergency',
    category: 'Medical & Triage',
    urgency: 'critical',
    icon: 'Siren',
    civicDomain: 'Urgent Care & Rapid Response',
    intentSummary: 'Critical emergency alert signaled by visitor.',
    clerkAction: 'Trigger counter emergency alert. Dispatch on-duty triage nurse or security escort immediately.',
    visitorAssurance: 'Emergency response activated. Medical team has been alerted.',
    recommendedNextSign: 'doctor',
    quickStaffReplies: ['Emergency team is on the way.', 'Please stay calm, help is right here.'],
  },
  doctor: {
    word: 'doctor',
    category: 'Medical & Triage',
    urgency: 'high',
    icon: 'Stethoscope',
    civicDomain: 'Hospital Triage & Consultation',
    intentSummary: 'Visitor is seeking an appointment or immediate consultation with a medical doctor.',
    clerkAction: 'Check on-duty triage schedule. Issue fast-track medical token and direct to Consultation Suite #2.',
    visitorAssurance: 'Doctor has been notified. You are registered for the next available medical consultation.',
    recommendedNextSign: 'wait',
    quickStaffReplies: ['The doctor will see you shortly.', 'Consultation room is through door 2.', 'Please fill out your symptom note.'],
  },
  pain: {
    word: 'pain',
    category: 'Medical & Triage',
    urgency: 'high',
    icon: 'Activity',
    civicDomain: 'Clinical Symptom Assessment',
    intentSummary: 'Visitor indicates physical discomfort, distress, or acute pain.',
    clerkAction: 'Provide a comfortable ergonomic chair. Offer a visual pain-scale rating chart (1-10) and notify triage.',
    visitorAssurance: 'We note you are in pain. Rapid clinical support is being assigned.',
    recommendedNextSign: 'doctor',
    quickStaffReplies: ['Please sit comfortably.', 'Point on the chart where it hurts.', 'Nurse is coming.'],
  },
  sick: {
    word: 'sick',
    category: 'Medical & Triage',
    urgency: 'high',
    icon: 'Thermometer',
    civicDomain: 'Public Health & Intake',
    intentSummary: 'Visitor reports feeling unwell, feverish, or experiencing illness symptoms.',
    clerkAction: 'Offer sanitized mask and water. Fast-track through intake to prevent waiting room distress.',
    visitorAssurance: 'Health assistance assigned. Moving you to priority triage desk.',
    recommendedNextSign: 'doctor',
    quickStaffReplies: ['Here is water and a sanitized mask.', 'Let us check your temperature.', 'Please sit here.'],
  },
  form: {
    word: 'form',
    category: 'Civic Administration',
    urgency: 'standard',
    icon: 'FileText',
    civicDomain: 'Paperwork & Registration Desk',
    intentSummary: 'Visitor is inquiring about, requesting, or submitting an official service form.',
    clerkAction: 'Provide Form B-12 (Accessibility Accommodated). Pre-highlight mandatory signature fields.',
    visitorAssurance: 'Standard civic application form retrieved. Staff will assist in completing each field.',
    recommendedNextSign: 'sign',
    quickStaffReplies: ['Here is the official form.', 'I will guide you through each section.', 'Only yellow boxes require your signature.'],
  },
  sign: {
    word: 'sign',
    category: 'Civic Administration',
    urgency: 'standard',
    icon: 'PenTool',
    civicDomain: 'Document Execution & Verification',
    intentSummary: 'Visitor needs to sign documents or asks where to place their signature.',
    clerkAction: 'Orient the signature tablet or paper document directly toward the visitor. Point to signature line with stylus.',
    visitorAssurance: 'Document ready for your signature on the highlighted line.',
    recommendedNextSign: 'thank you',
    quickStaffReplies: ['Please sign right here.', 'Take your time, no rush.', 'Signature verified successfully.'],
  },
  name: {
    word: 'name',
    category: 'Civic Administration',
    urgency: 'standard',
    icon: 'UserCheck',
    civicDomain: 'Identity Verification & Registration',
    intentSummary: 'Visitor is sharing their identity or requesting name registration on the service record.',
    clerkAction: 'Display identity input screen. Confirm spelling of full name against identity card or passport.',
    visitorAssurance: 'Identity details received. Record being updated in the municipal registry.',
    recommendedNextSign: 'appointment',
    quickStaffReplies: ['May I verify your ID card?', 'Thank you, name is logged.', 'Spelling verified.'],
  },
  appointment: {
    word: 'appointment',
    category: 'Civic Administration',
    urgency: 'standard',
    icon: 'Calendar',
    civicDomain: 'Booking & Schedule Coordination',
    intentSummary: 'Visitor is verifying an existing appointment time or booking a new service slot.',
    clerkAction: 'Query appointment database for today. Confirm appointment slot time and print verification token.',
    visitorAssurance: 'Appointment verified for today. You are next on the schedule.',
    recommendedNextSign: 'wait',
    quickStaffReplies: ['Your appointment is confirmed.', 'You are scheduled for 11:30 AM.', 'Booking new slot for you.'],
  },
  problem: {
    word: 'problem',
    category: 'Civic Administration',
    urgency: 'high',
    icon: 'HelpCircle',
    civicDomain: 'Grievance & Service Resolution',
    intentSummary: 'Visitor is encountering a service difficulty, discrepancy, or bureaucratic blocker.',
    clerkAction: 'Open grievance resolution ticket. Assign senior desk officer with written communication tablet.',
    visitorAssurance: 'Issue recorded. Senior resolution officer assigned to resolve this directly.',
    recommendedNextSign: 'help',
    quickStaffReplies: ['Let me fix this problem for you.', 'Checking your record details.', 'No penalty applies.'],
  },
  money: {
    word: 'money',
    category: 'Financial & Payment',
    urgency: 'standard',
    icon: 'CreditCard',
    civicDomain: 'Cashier & Payment Window',
    intentSummary: 'Visitor is making a fee payment, fee waiver query, or asking about financial transactions.',
    clerkAction: 'Present the high-contrast POS card reader or cashier receipt slip. Display exact amount clearly in large text.',
    visitorAssurance: 'Fee total displayed on customer terminal. Receipts generated automatically.',
    recommendedNextSign: 'thank you',
    quickStaffReplies: ['Total fee is displayed on the screen.', 'Card and contactless accepted.', 'Here is your official receipt.'],
  },
  wait: {
    word: 'wait',
    category: 'Queue & Navigation',
    urgency: 'standard',
    icon: 'Clock',
    civicDomain: 'Queue & Waiting Area Management',
    intentSummary: 'Visitor is acknowledging wait time or inquiring how long processing will take.',
    clerkAction: 'Issue priority vibrating pager or visual queue ticket with estimated duration (under 5 mins).',
    visitorAssurance: 'Estimated wait time is 4 minutes. Your token number will flash on Screen #1.',
    recommendedNextSign: 'here',
    quickStaffReplies: ['Estimated wait is 5 minutes.', 'Please relax in the waiting lounge.', 'We will notify you immediately.'],
  },
  here: {
    word: 'here',
    category: 'Queue & Navigation',
    urgency: 'courtesy',
    icon: 'MapPin',
    civicDomain: 'Station & Counter Location',
    intentSummary: 'Visitor indicates current counter presence or asks if this is the correct desk.',
    clerkAction: 'Confirm: "Yes, you are at the correct service counter." Offer a seat at this station.',
    visitorAssurance: 'You are at Counter #4 (Accessibility & Priority Support).',
    recommendedNextSign: 'now',
    quickStaffReplies: ['You are in the right place.', 'This counter handles all your requests.', 'Please have a seat.'],
  },
  now: {
    word: 'now',
    category: 'Queue & Navigation',
    urgency: 'standard',
    icon: 'Zap',
    civicDomain: 'Immediate Service Execution',
    intentSummary: 'Visitor requests immediate action or confirms readiness to proceed now.',
    clerkAction: 'Process request immediately without delay. Switch terminal to live intake.',
    visitorAssurance: 'Processing your request right now.',
    recommendedNextSign: 'please',
    quickStaffReplies: ['Processing right now.', 'Starting your verification immediately.', 'All set to proceed.'],
  },
  where: {
    word: 'where',
    category: 'Queue & Navigation',
    urgency: 'standard',
    icon: 'Compass',
    civicDomain: 'Facility Wayfinding & Directions',
    intentSummary: 'Visitor is asking for directions to a room, counter, restroom, or exit.',
    clerkAction: 'Display the visual facility floor map with high-visibility arrows pointing to target room.',
    visitorAssurance: 'Interactive floor plan displayed with clear navigation arrows.',
    recommendedNextSign: 'here',
    quickStaffReplies: ['Room 102 is down the left hallway.', 'Elevator is directly behind you.', 'Follow the green line on the floor.'],
  },
  please: {
    word: 'please',
    category: 'Dialogue & Civility',
    urgency: 'courtesy',
    icon: 'HeartHandshake',
    civicDomain: 'Respectful Public Dialogue',
    intentSummary: 'Visitor expressing polite request or attention.',
    clerkAction: 'Smile, acknowledge with welcoming nod, and proceed attentively.',
    visitorAssurance: 'With pleasure. We are fully at your service.',
    recommendedNextSign: 'form',
    quickStaffReplies: ['It is our pleasure.', 'Certainly, right away.', 'How may I assist?'],
  },
  'thank you': {
    word: 'thank you',
    category: 'Dialogue & Civility',
    urgency: 'courtesy',
    icon: 'Smile',
    civicDomain: 'Service Conclusion & Feedback',
    intentSummary: 'Visitor expressing gratitude and concluding interaction.',
    clerkAction: 'Return warm sign for "thank you" or bow head slightly. Hand completed paperwork packet.',
    visitorAssurance: 'You are very welcome. Have a wonderful day!',
    recommendedNextSign: 'here',
    quickStaffReplies: ['You are very welcome!', 'Have a great day!', 'Glad we could help today.'],
  },
  'thank_you': {
    word: 'thank you',
    category: 'Dialogue & Civility',
    urgency: 'courtesy',
    icon: 'Smile',
    civicDomain: 'Service Conclusion & Feedback',
    intentSummary: 'Visitor expressing gratitude and concluding interaction.',
    clerkAction: 'Return warm sign for "thank you" or bow head slightly. Hand completed paperwork packet.',
    visitorAssurance: 'You are very welcome. Have a wonderful day!',
    recommendedNextSign: 'here',
    quickStaffReplies: ['You are very welcome!', 'Have a great day!', 'Glad we could help today.'],
  },
  'thankyou': {
    word: 'thank you',
    category: 'Dialogue & Civility',
    urgency: 'courtesy',
    icon: 'Smile',
    civicDomain: 'Service Conclusion & Feedback',
    intentSummary: 'Visitor expressing gratitude and concluding interaction.',
    clerkAction: 'Return warm sign for "thank you" or bow head slightly. Hand completed paperwork packet.',
    visitorAssurance: 'You are very welcome. Have a wonderful day!',
    recommendedNextSign: 'here',
    quickStaffReplies: ['You are very welcome!', 'Have a great day!', 'Glad we could help today.'],
  },
  yes: {
    word: 'yes',
    category: 'Dialogue & Civility',
    urgency: 'courtesy',
    icon: 'Check',
    civicDomain: 'Affirmative Verification',
    intentSummary: 'Visitor confirms affirmation or agrees with question/option presented.',
    clerkAction: 'Record affirmative response. Proceed to next step in workflow.',
    visitorAssurance: 'Confirmed (Yes). Proceeding to next step.',
    recommendedNextSign: 'now',
    quickStaffReplies: ['Understood, proceeding.', 'Yes recorded.', 'Great, next step.'],
  },
  no: {
    word: 'no',
    category: 'Dialogue & Civility',
    urgency: 'courtesy',
    icon: 'X',
    civicDomain: 'Negative Verification / Alternative',
    intentSummary: 'Visitor declines or indicates negative response.',
    clerkAction: 'Acknowledge decline. Present alternate option or clarification prompt.',
    visitorAssurance: 'Declined (No). Exploring alternate options for you.',
    recommendedNextSign: 'more',
    quickStaffReplies: ['Understood, skipping this.', 'Would you prefer another option?', 'No problem at all.'],
  },
  more: {
    word: 'more',
    category: 'Dialogue & Civility',
    urgency: 'courtesy',
    icon: 'PlusCircle',
    civicDomain: 'Supplemental Services',
    intentSummary: 'Visitor has additional requests, more documents, or further questions.',
    clerkAction: 'Keep session open. Inquire if additional copies, stamps, or certifications are needed.',
    visitorAssurance: 'Session remains open. Please show your next request.',
    recommendedNextSign: 'form',
    quickStaffReplies: ['What else can I help with?', 'Take your time for additional requests.', 'Ready for your next document.'],
  },
};

export const CIVIC_SECTORS = [
  {
    id: 'all',
    name: 'Full Civic Lexicon (20 Signs)',
    description: 'Complete accessibility vocabulary for public service counters',
    words: Object.keys(CIVIC_CONTEXT_MAP),
  },
  {
    id: 'medical',
    name: 'Hospital & Emergency Triage',
    description: 'Urgent medical assistance, pain reporting, physician consultation',
    words: ['help', 'emergency', 'doctor', 'pain', 'sick'],
  },
  {
    id: 'admin',
    name: 'Municipal & Administrative Desk',
    description: 'Forms, legal signatures, identity verification, appointments',
    words: ['form', 'sign', 'name', 'appointment', 'problem'],
  },
  {
    id: 'banking',
    name: 'Cashier & Payment Services',
    description: 'Financial transactions, receipts, fee payments, queue tokens',
    words: ['money', 'sign', 'wait', 'form', 'thank you'],
  },
  {
    id: 'navigation',
    name: 'Wayfinding & Queue Management',
    description: 'Waiting estimates, desk locations, floor directions, timing',
    words: ['wait', 'here', 'now', 'where'],
  },
];

export function getCivicProtocol(word?: string): CivicActionProtocol {
  if (!word) return CIVIC_CONTEXT_MAP.help;
  const raw = word.toLowerCase().trim();
  const normalized = raw.replace(/_/g, ' ');
  return CIVIC_CONTEXT_MAP[normalized] || CIVIC_CONTEXT_MAP[raw] || CIVIC_CONTEXT_MAP.help;
}
